const express = require('express')
const authRouter = express.Router()
const register = require ('../controllers/authControllers')
authrouter.post('/signup',register)
authrouter.post('/signin',(req,res)=>{})
authrouter.post('/reset-password',(req,res)=>{})
authrouter.post('/new-password',(req,res)=>{})
authrouter.post('/refresh-token',refreshtoken)
authrouter.post('/logout',(req,res)=>{})